using UnityEngine;
using System.Collections.Generic;

namespace Strategy
{
    public class ClientStrategyLvl3 : MonoBehaviour
    {
        private GameObject _obstacle;
        private List<IManeuverBehaviour> _components = new List<IManeuverBehaviour>();

        private void SpawnObstacle()
        {
            _obstacle = GameObject.CreatePrimitive(PrimitiveType.Cube);
            _obstacle.tag = "Obstacle";
            _obstacle.AddComponent<Obstacle>();
            _obstacle.transform.position = new Vector3(0, 1, 40);
            ApplyRandomStrategies();
            _obstacle = GameObject.CreatePrimitive(PrimitiveType.Cube);
            _obstacle.tag = "Obstacle";
            _obstacle.AddComponent<Obstacle>();
            _obstacle.transform.position = new Vector3(-6, 1, 120);
            ApplyRandomStrategies();
            _obstacle = GameObject.CreatePrimitive(PrimitiveType.Cube);
            _obstacle.tag = "Obstacle";
            _obstacle.AddComponent<Obstacle>();
            _obstacle.transform.position = new Vector3(6, 1, 120);
            ApplyRandomStrategies();
            _obstacle = GameObject.CreatePrimitive(PrimitiveType.Cube);
            _obstacle.tag = "Obstacle";
            _obstacle.AddComponent<Obstacle>();
            _obstacle.transform.position = new Vector3(-3, 1, 160);
            ApplyRandomStrategies();
            _obstacle = GameObject.CreatePrimitive(PrimitiveType.Cube);
            _obstacle.tag = "Obstacle";
            _obstacle.AddComponent<Obstacle>();
            _obstacle.transform.position = new Vector3(3, 1, 160);
            ApplyRandomStrategies();
            _obstacle = GameObject.CreatePrimitive(PrimitiveType.Cube);
            _obstacle.tag = "Obstacle";
            _obstacle.AddComponent<Obstacle>();
            _obstacle.transform.position = new Vector3(-3, 1, 200);
            ApplyRandomStrategies();
            _obstacle = GameObject.CreatePrimitive(PrimitiveType.Cube);
            _obstacle.tag = "Obstacle";
            _obstacle.AddComponent<Obstacle>();
            _obstacle.transform.position = new Vector3(-1, 1, 200);
            ApplyRandomStrategies();
            _obstacle = GameObject.CreatePrimitive(PrimitiveType.Cube);
            _obstacle.tag = "Obstacle";
            _obstacle.AddComponent<Obstacle>();
            _obstacle.transform.position = new Vector3(3, 1, 200);
            ApplyRandomStrategies();
            _obstacle = GameObject.CreatePrimitive(PrimitiveType.Cube);
            _obstacle.tag = "Obstacle";
            _obstacle.AddComponent<Obstacle>();
            _obstacle.transform.position = new Vector3(6, 1, 220);
            ApplyRandomStrategies();
            _obstacle = GameObject.CreatePrimitive(PrimitiveType.Cube);
            _obstacle.tag = "Obstacle";
            _obstacle.AddComponent<Obstacle>();
            _obstacle.transform.position = new Vector3(4, 1, 224);
            ApplyRandomStrategies();
            _obstacle = GameObject.CreatePrimitive(PrimitiveType.Cube);
            _obstacle.tag = "Obstacle";
            _obstacle.AddComponent<Obstacle>();
            _obstacle.transform.position = new Vector3(2, 1, 228);
            ApplyRandomStrategies();
            _obstacle = GameObject.CreatePrimitive(PrimitiveType.Cube);
            _obstacle.tag = "Obstacle";
            _obstacle.AddComponent<Obstacle>();
            _obstacle.transform.position = new Vector3(0, 1, 232);
            ApplyRandomStrategies();
            _obstacle = GameObject.CreatePrimitive(PrimitiveType.Cube);
            _obstacle.tag = "Obstacle";
            _obstacle.AddComponent<Obstacle>();
            _obstacle.transform.position = new Vector3(-2, 1, 236);
            ApplyRandomStrategies();
            _obstacle = GameObject.CreatePrimitive(PrimitiveType.Cube);
            _obstacle.tag = "Obstacle";
            _obstacle.AddComponent<Obstacle>();
            _obstacle.transform.position = new Vector3(-6, 1, 260);
            ApplyRandomStrategies();
            _obstacle = GameObject.CreatePrimitive(PrimitiveType.Cube);
            _obstacle.tag = "Obstacle";
            _obstacle.AddComponent<Obstacle>();
            _obstacle.transform.position = new Vector3(0, 1, 260);
            ApplyRandomStrategies();
            _obstacle = GameObject.CreatePrimitive(PrimitiveType.Cube);
            _obstacle.tag = "Obstacle";
            _obstacle.AddComponent<Obstacle>();
            _obstacle.transform.position = new Vector3(6, 1, 260);
            ApplyRandomStrategies();
            _obstacle = GameObject.CreatePrimitive(PrimitiveType.Cube);
            _obstacle.tag = "Obstacle";
            _obstacle.AddComponent<Obstacle>();
            _obstacle.transform.position = new Vector3(-6, 1, 300);
            ApplyRandomStrategies();
            _obstacle = GameObject.CreatePrimitive(PrimitiveType.Cube);
            _obstacle.tag = "Obstacle";
            _obstacle.AddComponent<Obstacle>();
            _obstacle.transform.position = new Vector3(6, 1, 300);
            ApplyRandomStrategies();
            _obstacle = GameObject.CreatePrimitive(PrimitiveType.Cube);
            _obstacle.tag = "Obstacle";
            _obstacle.AddComponent<Obstacle>();
            _obstacle.transform.position = new Vector3(-6, 1, 320);
            ApplyRandomStrategies();
            _obstacle = GameObject.CreatePrimitive(PrimitiveType.Cube);
            _obstacle.tag = "Obstacle";
            _obstacle.AddComponent<Obstacle>();
            _obstacle.transform.position = new Vector3(0, 1, 320);
            ApplyRandomStrategies();
            _obstacle = GameObject.CreatePrimitive(PrimitiveType.Cube);
            _obstacle.tag = "Obstacle";
            _obstacle.AddComponent<Obstacle>();
            _obstacle.transform.position = new Vector3(6, 1, 320);
            ApplyRandomStrategies();
            _obstacle = GameObject.CreatePrimitive(PrimitiveType.Cube);
            _obstacle.tag = "Obstacle";
            _obstacle.AddComponent<Obstacle>();
            _obstacle.transform.position = new Vector3(0, 1, 360);
            ApplyRandomStrategies();
            _obstacle = GameObject.CreatePrimitive(PrimitiveType.Cube);
            _obstacle.tag = "Obstacle";
            _obstacle.AddComponent<Obstacle>();
            _obstacle.transform.position = new Vector3(-6, 1, 380);
            ApplyRandomStrategies();
            _obstacle = GameObject.CreatePrimitive(PrimitiveType.Cube);
            _obstacle.tag = "Obstacle";
            _obstacle.AddComponent<Obstacle>();
            _obstacle.transform.position = new Vector3(6, 1, 380);
            ApplyRandomStrategies();
            _obstacle = GameObject.CreatePrimitive(PrimitiveType.Cube);
            _obstacle.tag = "Obstacle";
            _obstacle.AddComponent<Obstacle>();
            _obstacle.transform.position = new Vector3(-3, 1, 400);
            ApplyRandomStrategies();
            _obstacle = GameObject.CreatePrimitive(PrimitiveType.Cube);
            _obstacle.tag = "Obstacle";
            _obstacle.AddComponent<Obstacle>();
            _obstacle.transform.position = new Vector3(3, 1, 400);
            ApplyRandomStrategies();
            _obstacle = GameObject.CreatePrimitive(PrimitiveType.Cube);
            _obstacle.tag = "Obstacle";
            _obstacle.AddComponent<Obstacle>();
            _obstacle.transform.position = new Vector3(-3, 1, 440);
            ApplyRandomStrategies();
            _obstacle = GameObject.CreatePrimitive(PrimitiveType.Cube);
            _obstacle.tag = "Obstacle";
            _obstacle.AddComponent<Obstacle>();
            _obstacle.transform.position = new Vector3(-1, 1, 440);
            ApplyRandomStrategies();
            _obstacle = GameObject.CreatePrimitive(PrimitiveType.Cube);
            _obstacle.tag = "Obstacle";
            _obstacle.AddComponent<Obstacle>();
            _obstacle.transform.position = new Vector3(3, 1, 440);
            ApplyRandomStrategies();
            _obstacle = GameObject.CreatePrimitive(PrimitiveType.Cube);
            _obstacle.tag = "Obstacle";
            _obstacle.AddComponent<Obstacle>();
            _obstacle.transform.position = new Vector3(-6, 1, 480);
            ApplyRandomStrategies();
            _obstacle = GameObject.CreatePrimitive(PrimitiveType.Cube);
            _obstacle.tag = "Obstacle";
            _obstacle.AddComponent<Obstacle>();
            _obstacle.transform.position = new Vector3(6, 1, 480);
            ApplyRandomStrategies();
            _obstacle = GameObject.CreatePrimitive(PrimitiveType.Cube);
            _obstacle.tag = "Obstacle";
            _obstacle.AddComponent<Obstacle>();
            _obstacle.transform.position = new Vector3(-4, 1, 484);
            ApplyRandomStrategies();
            _obstacle = GameObject.CreatePrimitive(PrimitiveType.Cube);
            _obstacle.tag = "Obstacle";
            _obstacle.AddComponent<Obstacle>();
            _obstacle.transform.position = new Vector3(4, 1, 484);
            ApplyRandomStrategies();
            _obstacle = GameObject.CreatePrimitive(PrimitiveType.Cube);
            _obstacle.tag = "Obstacle";
            _obstacle.AddComponent<Obstacle>();
            _obstacle.transform.position = new Vector3(-2, 1, 488);
            ApplyRandomStrategies();
            _obstacle = GameObject.CreatePrimitive(PrimitiveType.Cube);
            _obstacle.tag = "Obstacle";
            _obstacle.AddComponent<Obstacle>();
            _obstacle.transform.position = new Vector3(2, 1, 488);
            ApplyRandomStrategies();
            _obstacle = GameObject.CreatePrimitive(PrimitiveType.Cube);
            _obstacle.tag = "Obstacle";
            _obstacle.AddComponent<Obstacle>();
            _obstacle.transform.position = new Vector3(-2, 1, 528);
            ApplyRandomStrategies();
            _obstacle = GameObject.CreatePrimitive(PrimitiveType.Cube);
            _obstacle.tag = "Obstacle";
            _obstacle.AddComponent<Obstacle>();
            _obstacle.transform.position = new Vector3(2, 1, 528);
            ApplyRandomStrategies();
            _obstacle = GameObject.CreatePrimitive(PrimitiveType.Cube);
            _obstacle.tag = "Obstacle";
            _obstacle.AddComponent<Obstacle>();
            _obstacle.transform.position = new Vector3(-4, 1, 532);
            ApplyRandomStrategies();
            _obstacle = GameObject.CreatePrimitive(PrimitiveType.Cube);
            _obstacle.tag = "Obstacle";
            _obstacle.AddComponent<Obstacle>();
            _obstacle.transform.position = new Vector3(4, 1, 532);
            ApplyRandomStrategies();
            _obstacle = GameObject.CreatePrimitive(PrimitiveType.Cube);
            _obstacle.tag = "Obstacle";
            _obstacle.AddComponent<Obstacle>();
            _obstacle.transform.position = new Vector3(-6, 1, 536);
            ApplyRandomStrategies();
            _obstacle = GameObject.CreatePrimitive(PrimitiveType.Cube);
            _obstacle.tag = "Obstacle";
            _obstacle.AddComponent<Obstacle>();
            _obstacle.transform.position = new Vector3(6, 1, 536);
            ApplyRandomStrategies();
            _obstacle = GameObject.CreatePrimitive(PrimitiveType.Cube);
            _obstacle.tag = "Obstacle";
            _obstacle.AddComponent<Obstacle>();
            _obstacle.transform.position = new Vector3(-6, 1, 560);
            ApplyRandomStrategies();
            _obstacle = GameObject.CreatePrimitive(PrimitiveType.Cube);
            _obstacle.tag = "Obstacle";
            _obstacle.AddComponent<Obstacle>();
            _obstacle.transform.position = new Vector3(0, 1, 560);
            ApplyRandomStrategies();
            _obstacle = GameObject.CreatePrimitive(PrimitiveType.Cube);
            _obstacle.tag = "Obstacle";
            _obstacle.AddComponent<Obstacle>();
            _obstacle.transform.position = new Vector3(6, 1, 560);
            ApplyRandomStrategies();
            _obstacle = GameObject.CreatePrimitive(PrimitiveType.Cube);
            _obstacle.tag = "Obstacle";
            _obstacle.AddComponent<Obstacle>();
            _obstacle.transform.position = new Vector3(4, 1, 600);
            ApplyRandomStrategies();
            _obstacle = GameObject.CreatePrimitive(PrimitiveType.Cube);
            _obstacle.tag = "Obstacle";
            _obstacle.AddComponent<Obstacle>();
            _obstacle.transform.position = new Vector3(4, 1, 600);
            ApplyRandomStrategies();
            _obstacle = GameObject.CreatePrimitive(PrimitiveType.Cube);
            _obstacle.tag = "Obstacle";
            _obstacle.AddComponent<Obstacle>();
            _obstacle.transform.position = new Vector3(0, 1, 640);
            ApplyRandomStrategies();
            _obstacle = GameObject.CreatePrimitive(PrimitiveType.Cube);
            _obstacle.tag = "Obstacle";
            _obstacle.AddComponent<Obstacle>();
            _obstacle.transform.position = new Vector3(-6, 1, 680);
            ApplyRandomStrategies();
            _obstacle = GameObject.CreatePrimitive(PrimitiveType.Cube);
            _obstacle.tag = "Obstacle";
            _obstacle.AddComponent<Obstacle>();
            _obstacle.transform.position = new Vector3(0, 1, 680);
            ApplyRandomStrategies();
            _obstacle = GameObject.CreatePrimitive(PrimitiveType.Cube);
            _obstacle.tag = "Obstacle";
            _obstacle.AddComponent<Obstacle>();
            _obstacle.transform.position = new Vector3(6, 1, 680);
            ApplyRandomStrategies();
        }

        private void ApplyRandomStrategies()
        {
            _components.Add(_obstacle.AddComponent<WeavingManeuver>());
            _components.Add(_obstacle.AddComponent<BoppingManeuver>());

            int index = Random.Range(0, _components.Count);

            _obstacle.GetComponent<Obstacle>().ApplyStrategy(_components[index]);
        }

        void Awake()
        {
            SpawnObstacle();
        }
    }
}